-- 9. Devido ao aumento do índice IGPM (Índece Geral Dos Preços), a empresa reajustou os valores 
--    dos planos básicos em 10%, dos planos executivos em 5% e dos planos Máster em 3 %. Atualize 
--    os valores na tabela planos.

# ATUALIZANDO VALORES DOS PLANOS BÁSICOS:
SELECT NUMERO, VALOR FROM PLANOS WHERE DESCRICAO LIKE '%BASICO%';
UPDATE PLANOS
SET VALOR = VALOR + ROUND((VALOR/100) * 10)
WHERE DESCRICAO LIKE '%BASICO%';
-- CONSULTANDO ATUALIZAÇÃO
SELECT NUMERO, VALOR FROM PLANOS 
WHERE DESCRICAO LIKE '%BASICO%';
#-------------------------------------------------------------------#
# ATUALIZANDO VALORES DOS PLANOS EXECUTIVOS:
SELECT NUMERO, VALOR FROM PLANOS WHERE DESCRICAO LIKE '%EXECUTIVO%';
UPDATE PLANOS
SET VALOR = VALOR + ROUND((VALOR/100) * 5)
WHERE DESCRICAO LIKE '%EXECUTIVO%';
-- CONSULTANDO ATUALIZAÇÃO
SELECT NUMERO, VALOR FROM PLANOS 
WHERE DESCRICAO LIKE '%EXECUTIVO%';
#-------------------------------------------------------------------#
# ATUALIZANDO VALORES DOS PLANOS MASTER:
SELECT NUMERO, VALOR FROM PLANOS WHERE DESCRICAO LIKE '%MASTER%';
UPDATE PLANOS
SET VALOR = VALOR + ROUND((VALOR/100) * 3)
WHERE DESCRICAO LIKE '%MASTER%';
-- CONSULTANDO ATUALIZAÇÃO
SELECT NUMERO, VALOR FROM PLANOS 
WHERE DESCRICAO LIKE '%MASTER%';