-- 10. O associado PEDRO JOSE DE OLIVEIRA alterou seu plano de B1 para E3. Faça a devida atualização.
UPDATE 
	ASSOCIADOS
SET 
	PLANO = 'E3'
WHERE 
	NOME LIKE '%PEDRO JOSE DE OLIVEIRA%';
-- CONSULTANDO ATUALIZAÇÃO 
SELECT * FROM ASSOCIADOS
WHERE NOME LIKE '%PEDRO JOSE%';