-- 14. Quais são os associados que possuem plano dos tipos Básico e Máster?
SELECT
	ASSOCIADOS.NOME,
    ASSOCIADOS.CIDADE,
    ASSOCIADOS.PLANO,
    PLANOS.DESCRICAO
FROM 
	ASSOCIADOS
JOIN PLANOS
ON ASSOCIADOS.PLANO = PLANOS.NUMERO
WHERE
	PLANOS.DESCRICAO
	LIKE 
		'%BASICO%' OR
	PLANOS.DESCRICAO
	LIKE
		'%MASTER%';